Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8056"
    vb.cpus = 4
    config.vm.provider :virtualbox do |vb|
        vb.name = "OpsMx-Spinnaker"
    end
  end
  config.vm.provision "shell", path: "opsmx-install-spinnaker.sh"
  # config.disksize.size = '30GB'
end
